### ISSUE TITLE
Give credit modal lists wrong employee in text

### ISSUE THREAD

**Issue by tfullington-isobar** [isobar-techchallenge/isobar-a9f8d858-fb06-4865-833f-f03fc2d03cd1#67]
<img width="1004" alt="screen shot 2016-09-14 at 10 56 16 am" src="https://cloud.githubusercontent.com/assets/22199193/18519711/7db60ebe-7a6a-11e6-8865-57eae54c1cc6.png">

1. Logged in as test user
2. Giving credit/kudo to Dmitriy 
3. Text in blue modal shows I'm giving credit to myself (the logged in user)

**Comment by adam-dhs-isobar** [comment]
This will be in the build shortly.
