### ISSUE TITLE
Browser tab title only shows 'Title'

### ISSUE THREAD

**Issue by tfullington-isobar** [isobar-techchallenge/isobar-a9f8d858-fb06-4865-833f-f03fc2d03cd1#70]
We need the app name or DHS FLASH or anything to show up as the tab title.
<img width="373" alt="screen shot 2016-09-14 at 11 11 06 am" src="https://cloud.githubusercontent.com/assets/22199193/18520120/1cee0dd2-7a6c-11e6-98db-d84020855247.png">

**Comment by adam-dhs-isobar** [comment]
We can update it with the app name but it's updated for now.
