### ISSUE TITLE
Kudo count on profile page should move below picture (colliding chin issue with photos)

### ISSUE THREAD

**Issue by tfullington-isobar** [isobar-techchallenge/isobar-a9f8d858-fb06-4865-833f-f03fc2d03cd1#71]
The kudo count on the employee cards has shifted down to avoid overlapping with people's faces but this issue still happens on the profile page photo. Ideally we shift the kudo count down to avoid the issue.

<img width="575" alt="screen shot 2016-09-14 at 11 22 04 am" src="https://cloud.githubusercontent.com/assets/22199193/18520456/7f10645a-7a6d-11e6-825d-6e07a02d9603.png">

**Comment by adam-dhs-isobar** [comment]
We've moved this to the bottom of the card now.
